apiVersion: v1
kind: Service
metadata:
  name: {{ include "novu.web.fullname" . }}
  labels:
    app: {{ include "novu.name" . }}
    component: web
spec:
  type: ClusterIP
  selector:
    app: {{ include "novu.name" . }}
    component: web
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.web.port }}
      targetPort: 4200