apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "novu.api.fullname" . }}
  labels:
    app: {{ include "novu.name" . }}
    component: api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "novu.name" . }}
      component: api
  template:
    metadata:
      labels:
        app: {{ include "novu.name" . }}
        component: api
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: {{ include "novu.fullname" . }}-config
            - secretRef:
                name: {{ include "novu.fullname" . }}-secret
          env:
            - name: DISABLE_USER_REGISTRATION
              value: "{{ .Values.global.env.disableUserRegistration }}"
            - name: FRONT_BASE_URL
              value: "{{ .Values.global.env.frontBaseUrl }}"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ include "redis.fullname" . }}"
                  key: redis-password
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "mongodb.fullname" . }}-svcbind-root
                  key: uri
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /v1/health-check
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /v1/health-check
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always