apiVersion: v1
kind: Service
metadata:
  name: {{ include "novu.api.fullname" . }}
  labels:
    app: {{ include "novu.name" . }}
    component: api
spec:
  type: ClusterIP
  selector:
    app: {{ include "novu.name" . }}
    component: api
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.api.port }}
      targetPort: 3000