{{- if .Values.ingress.enabled -}}
{{- $fullName := include "novu.fullname" . -}}
{{- $svcPortApi := .Values.api.port -}}
{{- $svcPortWeb := .Values.web.port -}}
{{- $svcPortWs := .Values.ws.port -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "novu.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - api.{{ .Values.ingress.host }}
      secretName: api.{{ .Values.ingress.tls.secretName }}
    - hosts:
        - web.{{ .Values.ingress.host }}
      secretName: web.{{ .Values.ingress.tls.secretName }}
    - hosts:
        - ws.{{ .Values.ingress.host }}
      secretName: ws.{{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    - host: api.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "novu.api.fullname" . }}
                port:
                  number: {{ $svcPortApi }}
    - host: web.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "novu.web.fullname" . }}
                port:
                  number: {{ $svcPortWeb }}
    - host: ws.{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "novu.ws.fullname" . }}
                port:
                  number: {{ $svcPortWs }}
{{- end }}
