apiVersion: v1
kind: Secret
metadata:
  name: {{ include "novu.fullname" . }}-secret
  labels:
    {{- include "novu.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.global.env.secret.jwtSecret | b64enc | quote }}
  STORE_ENCRYPTION_KEY: {{ .Values.global.env.secret.storageKey | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.env.aws.secretAccessKey | b64enc | quote }}
  SENTRY_DSN: {{ .Values.global.env.sentry.dsn | b64enc | quote }}
  NEW_RELIC_LICENSE_KEY: {{ .Values.global.env.newRelic.licenseKey | b64enc | quote }}
  NOVU_SECRET_KEY: {{ .Values.global.env.secret.novuSecretKey | b64enc | quote }}